services:
  - type: web
    name: multi-agent-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT dashboard:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PUBLIC_KEY
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: FORIO_ORG
        value: mitcams
      - key: FORIO_PROJECT
        value: cyberriskmanagement-ransomeware-2023
